### ISSUE TITLE
SIGN_SECRET could not be empty

### ISSUE THREAD

**Issue by yzs981130** [lawvs/lark-bot-worker#1]
Really amazing work and clear coding structure! 

I find a problem when I use lark webhook without a sign. It seems that the wrangler cannot put empty str as a secret and raises the following errors:
```
Error: Your secret cannot be empty.
Enter the secret text you'd like assigned to the variable SIGN_SECRET on the script named robot:
```
To keep the simplicity of using wrangler action, I recommend stating that SIGN_SECRET is necessary in the docs.

And any plans to support other Gitlab triggers? Like push?

**Comment by lawvs** [comment]
Thanks for your feedback! I fix the secret empty error by upgrade [wrangler-action](https://github.com/cloudflare/wrangler-action) to version 2.0

For more details, see https://github.com/lawvs/lark-bot-worker/compare/16fedce81e9e5960d0d3f1d895f69d440b8d1afb~~~...16fedce81e9e5960d0d3f1d895f69d440b8d1afb

> And any plans to support other Gitlab triggers? Like push?

push event may be too noisy for many active projects, can you elaborate on the usage scenarios?

**Comment by yzs981130** [comment]
Thanks for the quick response!

> push event may be too noisy for many active projects, can you elaborate on the usage scenarios?

Yeah, it indeed could be annoying, and Gitlab adds a branch filter in the webhook settings. My personal demand is just to get a notification from Lark directly about the code has been updated without checking Gitlab. It will be fine just keeping it.
